#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8  

~/.config/polybar/launch.sh  &
compton --config /home/wuxxf/.config/compton/compton.conf &
feh --bg-fill ~/Wallpapers/Fumi.jpg &
wmname LG3D &
dunst &

bspc config border_width         0
bspc config window_gap           4.8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a jetbrains-studio state=floating
bspc rule -a jetbrains-pycharm-ce state=floating
bspc rule -a jetbrains-idea-ce state=floating
bspc rule -a Eclipse state=floating
bspc rule -a Java state=floating
bspc rule -a Audacious state=floating
bspc rule -a Brackets state=tiled
bspc rule -a Steam state=floating
bspc rule -a Anki:anki state=floating
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a VirtualBox state=floating
bspc rule -a Pulseaudio-equalizer-gtk state=floating