#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

pkill polybar
~/.config/polybar/launch.sh --forest &

compton --config /home/wuxxf/.config/compton/compton.conf &
feh --bg-fill ~/Pictures/Wallpapers/Cherry.jpg &
wmname LG3D &

batsignal -w 20 -c 5 -f 100 &
exec mpd &
xsetroot -cursor_name left_ptr
killall redshift &
redshift &

pkill clipit
clipit &
pkill sxhkd
sxhkd &
pkill dunst
dunst &

bspc config border_width         0
bspc config window_gap           2
bspc config split_ratio          0.52

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc config focused_border_color  #FFFFFF
bspc config normal_border_color   #FFFFFF
bspc config active_border_color   #FFFFFF
bspc config presel_feedback_color #FFFFFF

bspc rule -a Kitty desktop='^1' follow=on focus=on
bspc rule -a Firefox desktop='^2' follow=on focus=on
bspc rule -a Google-chrome desktop='^2' follow=on focus=on
bspc rule -a Opera desktop='^2' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^2' follow=on focus=on
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a File-roller desktop='^3' follow=on focus=on
bspc rule -a Geany desktop='^4' follow=on focus=on
bspc rule -a Font-manager desktop='^5' state=tiled follow=on focus=on
bspc rule -a Evince desktop='^5' follow=on focus=on
bspc rule -a Gucharmap desktop='^5' follow=on focus=on
bspc rule -a Audacity desktop='^6' follow=on focus=on
bspc rule -a Vlc desktop='^6' follow=on focus=on
bspc rule -a mpv desktop='^6' follow=on focus=on
bspc rule -a Gimp desktop='^7' follow=on focus=on
bspc rule -a Oomox desktop='^7' follow=on focus=on
bspc rule -a Lxappearance desktop='^8' state=floating follow=on
bspc rule -a GParted desktop='^8' follow=on focus=on
bspc rule -a Pavucontrol desktop='^8' state=floating follow=on
bspc rule -a Viewnior state=floating follow=on

